# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   database: myapp_development
#   username: myapp
#   password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

# test:
#   database: myapp_test
#   username: myapp
#   password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

# production:
#     <<: *default
#     database: <%= ENV['RDS_DB_NAME'] %>
#     username: <%= ENV['RDS_USERNAME'] %>
#     password: <%= ENV['RDS_PASSWORD'] %>
#     host: <%= ENV['RDS_HOSTNAME'] %>
#     port: <%= ENV['RDS_PORT'] %>
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: myapp_development
  username: rocali
  password: asdw


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: myapp_test
  username: rocali
  password: asdw

production:
  <<: *default
  database: myapp_prod
  username: rocali
  password: asdw
